import { auth } from "@superset/auth/server";
import { findOrgMembership } from "@superset/db/utils";

import { env } from "@/env";
import { createSignedState, verifySignedState } from "@/lib/oauth-state";

export async function GET(request: Request) {
	const url = new URL(request.url);
	let userId: string;
	let organizationId: string;

	const preAuth = url.searchParams.get("pre_auth");

	if (preAuth) {
		// Desktop flow: verify the pre-auth token generated by /start endpoint.
		// This avoids requiring a browser-based sign-in.
		const verified = verifySignedState(preAuth);
		if (!verified) {
			return Response.json(
				{ error: "Invalid or expired pre_auth token" },
				{ status: 401 },
			);
		}
		userId = verified.userId;
		organizationId = verified.organizationId;
	} else {
		// Web flow: verify via session cookie.
		const session = await auth.api.getSession({
			headers: request.headers,
		});

		if (!session?.user) {
			return Response.json({ error: "Unauthorized" }, { status: 401 });
		}

		const orgId = url.searchParams.get("organizationId");
		if (!orgId) {
			return Response.json(
				{ error: "Missing organizationId parameter" },
				{ status: 400 },
			);
		}

		userId = session.user.id;
		organizationId = orgId;

		const membership = await findOrgMembership({ userId, organizationId });
		if (!membership) {
			return Response.json(
				{ error: "User is not a member of this organization" },
				{ status: 403 },
			);
		}
	}

	const state = createSignedState({ organizationId, userId });

	const linearAuthUrl = new URL("https://linear.app/oauth/authorize");
	linearAuthUrl.searchParams.set("client_id", env.LINEAR_CLIENT_ID);
	linearAuthUrl.searchParams.set(
		"redirect_uri",
		`${env.NEXT_PUBLIC_API_URL}/api/integrations/linear/callback`,
	);
	linearAuthUrl.searchParams.set("response_type", "code");
	linearAuthUrl.searchParams.set("scope", "read,write,issues:create");
	linearAuthUrl.searchParams.set("state", state);

	return Response.redirect(linearAuthUrl.toString());
}
